# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout
---
# playbook.yml

- hosts: all
  connection: ssh
  gather_facts: yes
  become: true
  vars_files:
    - "vars.yml"
  roles:
    - geerlingguy.firewall
    - geerlingguy.git
    - apolloclark.nano-highlighting

    - apolloclark.osquery
    - geerlingguy.java
    - apolloclark.elasticsearch
    - apolloclark.logstash
    - apolloclark.kibana
    - apolloclark.auditbeat
    - apolloclark.filebeat
    - apolloclark.packetbeat
    - apolloclark.metricbeat
    - apolloclark.heartbeat
